---
- name: Applies the standard configuration
  hosts: [ localhost ]
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get hostname
      debug:
        msg: '{{ ansible_hostname }}'
      tags:
        - always

    - name: Ensure groups exists
      ansible.builtin.group:
        name: admins
        state: present

    - name: Ensure groups exists
      ansible.builtin.group:
        name: developers
        state: present

    - name: Create standard user and add to specific groups
      ansible.builtin.user:
        name: user1
        shell: /bin/bash
        groups: admins,developers
        append: yes

    - name: Create a 2048-bit SSH key for user 'user1'
      ansible.builtin.user:
        name: user1
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Install Podman and related tools
      ansible.builtin.dnf:
        name: '@container-tools:ol8'
        state: present

    - name: Configure Podman to use netavark as network backend
      ansible.builtin.replace:
        path: /usr/share/containers/containers.conf
        regexp: 'network_backend = "cni"'
        replace: 'network_backend = "netavark"'

    - name: Run NGINX container image
      containers.podman.podman_container:
        name: my-ol9
        image: ghcr.io/oracle/oraclelinux9-nginx:1.20
        state: started
        detach: yes
        expose:
          - '80'
          - '443'
        publish:
          - '80:80'

    - name: Ensure firewalld is enabled and started
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true

    - name: Allow web traffic on port 80
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

    - name: Check how long the computer has been up and running
      command: uptime
      register: uptime_output
      changed_when: False

    - debug:
        var: uptime_output.stdout_lines

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install yum-utils required by reboot check
      ansible.builtin.dnf:
        name: yum-utils
        state: latest

    - name: Check if a reboot is required # requires yum-utils
      ansible.builtin.command: needs-restarting -r
      register: reg_reboot_required
      ignore_errors: yes
      failed_when: false
      changed_when: reg_reboot_required.rc != 0

    - debug:
        msg: "A reboot is required to finish updating this system."
      when: reg_reboot_required.rc != 0