---
- name: Applies the standard configuration
  hosts: [ localhost ]
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3

  roles:
    - get_hostname
    - users
    - containers
    - uptime
    - update_packages