---
- name: Update packages on wireguard server
  hosts:
    - localhost
  become: yes
  roles:
    - role: users
    - role: containers
    - role: uptime
    - role: update_packages
  tasks:
    - name: Get hostname
      debug:
        msg: '{{ ansible_hostname }}'
      tags:
        - always