# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/8"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"

  config.ssh.extra_args = ["-t", "cd /vagrant; bash --login"]

  config.vm.provision "shell", inline: <<-SHELL
    # Install Ansible
    dnf install -y oraclelinux-automation-manager-release-el8
    dnf install -y ansible
  SHELL

  # config.vm.provision "shell", inline: "dnf module install -y python39"
  # config.vm.provision "shell", inline: "python3 -m pip install --user ansible", privileged: false
end
