- name: Install Podman and related tools
  ansible.builtin.dnf:
    name: '@container-tools:ol8'
    state: present

- name: Configure Podman to use netavark as network backend
  ansible.builtin.replace:
    path: /usr/share/containers/containers.conf
    regexp: 'network_backend = "cni"'
    replace: 'network_backend = "netavark"'

- name: Run NGINX container image
  containers.podman.podman_container:
    name: my-ol9
    image: ghcr.io/oracle/oraclelinux9-nginx:1.20
    state: started
    detach: yes
    expose:
      - '80'
      - '443'
    publish:
      - '80:80'

- name: Ensure firewalld is enabled and started
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Allow web traffic on port 80
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled