```yaml title=playbook.yml
---
- name: Applies the standard configuration
  hosts:
    - region1
    - region2
    - region3
    
  tasks:
    
    # - debug:
    #     msg: '{{ ansible_hostname }}'

    - name: Ensure user1 is present
      win_user:
        name: user1
        fullname: User 1
        password: '{{ user1_secret }}'
        state: present
        user_cannot_change_password: yes
        password_never_expires: yes
        groups:
          - Users

    - name: Ensure admin is present
      win_user:
        name: admin
        fullname: Administrator
        password: '{{ admin_secret }}'
        state: present
        password_never_expires: yes
        groups:
          - Administrators

    - name: Ensure profile exists for user1
      win_user_profile:
        username: user1
        state: present

    - name: Copy acme folder
      win_copy:
        src: ./acme/
        dest: C:\acme\

    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present
        source: https://chocolatey.org/install.ps1
      when: ansible_facts['os_family'] == "Windows"

    - name: Install bginfo
      win_chocolatey:
        name: bginfo

    - name: Clear out existing tasks for bginfo
      community.windows.win_scheduled_task:
        name: Start bginfo
        state: absent

    - name: Create a task to start bginfo
      community.windows.win_scheduled_task:
        name: Start bginfo
        description: Applies the bginfo configuration
        actions:
          - path: Powershell.exe
            arguments: 'C:\ProgramData\chocolatey\bin\bginfo.exe C:\acme\bginfo\logon.bgi /silent /timer:0 /nolicprompt'
        triggers:
          - type: registration
          - type: logon
        group: Users
        disallow_start_if_on_batteries: false
        state: present

    - name: Install software
      win_chocolatey:
        name:
        - googlechrome
        - libreoffice-still
        - silverlight
        - dropbox

    - name: Install HP M479fdw Printer # Apparently this needs to be installed first (before the HP M201dw)
      win_chocolatey:
        name: printer-hp-m479fdw
        package_params: '/ipaddress:192.168.2.200'
        state: present
        source: C:\acme\chocolatey\
      tags:
        - m479
        
    - name: Install HP LaserJet Pro M201dw Printer # Using HP Universal Print Drivers
      win_chocolatey:
        name: printer-hp-upd
        package_params: '/ipaddress:192.168.2.201 /name:"HP LaserJet Pro M201dw"'
        state: present
        source: C:\acme\chocolatey\

    - name: Install TightVNC
      win_chocolatey:
        name: tightvnc
        install_args: 'SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD={{ vnc_admin_secret }} SET_VIEWONLYPASSWORD=1 VALUE_OF_VIEWONLYPASSWORD={{ vnc_view_secret }} SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD={{ vnc_admin_secret }} SET_REMOVEWALLPAPER=1 VALUE_OF_REMOVEWALLPAPER=0 SET_RUNCONTROLINTERFACE=1 VALUE_OF_RUNCONTROLINTERFACE=0'
        state: reinstalled
      when: ansible_facts['os_family'] == "Windows"
```