- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Check if a reboot is required # requires yum-utils
  ansible.builtin.command: needs-restarting -r
  register: reg_reboot_required
  ignore_errors: yes
  failed_when: false
  changed_when: reg_reboot_required.rc != 0

- debug:
    msg: "A reboot is required to finish updating this system."
  when: reg_reboot_required.rc != 0