- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: yes
  become_method: sudo

- name: Check if a reboot is required # requires yum-utils
  ansible.builtin.command: needs-restarting -r
  register: reg_reboot_required
  ignore_errors: yes
  failed_when: false
  changed_when: reg_reboot_required.rc != 0

- name: Prompt to reboot server
  pause:
    prompt: A reboot is required to complete the update, do you wish to continue (yes/no)?
  when: reg_reboot_required.rc != 0
  changed_when: confirm_reboot.user_input | bool
  notify:
    - Reboot server
  register: confirm_reboot