# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/7"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provision "file", source: "answer-file.txt", destination: "/tmp/answer-file.txt"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", path: "first-user.sh"
  config.vm.provision "shell", inline: "echo Access Oracle Linux Manager at https://192.168.56.10"
end
