- name: Ensure groups exists
  ansible.builtin.group:
    name: admins
    state: present

- name: Ensure groups exists
  ansible.builtin.group:
    name: developers
    state: present

- name: Create standard user and add to specific groups
  ansible.builtin.user:
    name: user1
    shell: /bin/bash
    groups: admins,developers
    append: yes

- name: Create a 2048-bit SSH key for user 'user1'
  ansible.builtin.user:
    name: user1
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa