services:
  wordpress01:
    image: wordpress
    container_name: wordpress01
    depends_on:
      wordpress01-db:
        condition: service_healthy
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress01-db
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: mysqlpw
      WORDPRESS_DB_NAME: mysqldb

  wordpress01-db:
    image: mysql:8-oracle
    container_name: wordpress01-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myqlrootpw
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mysqlpw
      MYSQL_DATABASE: mysqldb
    volumes:
      - ./data/init:/docker-entrypoint-initdb.d # Initialization scripts
      - wordpress01-db-data:/var/lib/mysql #Data directory
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  wordpress01-db-data: